name: Production-GraphRAG
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h0ad9c76_9
  - ca-certificates=2026.1.4=h4c7d964_0
  - libexpat=2.7.4=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - liblzma=5.8.2=hfd05255_0
  - libsqlite=3.51.2=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.6.1=hf411b9b_1
  - pip=26.0.1=pyh8b19718_0
  - python=3.10.19=hc20f281_3_cpython
  - setuptools=82.0.0=pyh332efcf_0
  - tk=8.6.13=h6ed50ae_3
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - wheel=0.46.3=pyhd8ed1ab_0
  - pip:
      - accelerate==0.33.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - datasets==4.4.2
      - dill==0.4.0
      - distro==1.9.0
      - exceptiongroup==1.3.1
      - faiss-cpu==1.9.0
      - filelock==3.20.3
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.4.2
      - numpy==1.26.4
      - omegaconf==2.3.0
      - openai==2.15.0
      - packaging==25.0
      - pandas==2.3.3
      - peft==0.12.0
      - pillow==12.0.0
      - pluggy==1.6.0
      - propcache==0.4.1
      - protobuf==6.33.4
      - psutil==7.2.1
      - pyarrow==22.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentence-transformers==5.2.0
      - sentencepiece==0.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.19.1
      - tomli==2.4.0
      - torch==2.4.1+cu121
      - torchaudio==2.4.1+cu121
      - torchvision==0.19.1+cu121
      - tqdm==4.67.1
      - transformers==4.44.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - uvicorn==0.41.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: E:\conda\envs\Production-GraphRAG
